### ISSUE TITLE
Rendering the completely mutated graph on the page

### ISSUE THREAD

**Issue by IshaniSanturkar** [googleinterns/step49-2020#8]

**Comment by EatingW** [comment]
Poker planning notes:

- Almost done
- Test mutations file, going through the list of mutations, and get a completely mutated graph
- Convert the graph to json
- Use cytoscape.js to parse json and display the graph
- How to consider this done? 
  - display a graph on the devserver page [done]
  - unit test for the mutations [done]
  - unit test for json? There is a function graphToJson in DataServelet. Write unit tests for this function by passing in a graph and comparing the resulting json string. 
  - consider having a screenshot test for the rendered graph? [might not be necessary]
      use a test runner to take a screenshot and compare it with a golden. Not necessary because it should be sufficient to assert the json is correct.

Proposed points: 4
